### ISSUE TITLE
Дописать тестов на shared_ptr

### ISSUE THREAD

**Issue by lejabque** [CPP-KT/shared-ptr-task#1]

**Comment by Dogzik** [comment]
![image](https://user-images.githubusercontent.com/26696217/193460072-da6b9011-89be-4a2f-b7db-27fcc8ad5407.png)

**Comment by Dogzik** [comment]
Тест на `weak_ptr& operator=(const shared_ptr&)`, где у shared такой же контрольный блок как у прошлого weak

**Comment by Dogzik** [comment]
![image](https://user-images.githubusercontent.com/26696217/193460156-80a10c27-669d-4ee6-81cb-0103f13877b1.png)

**Comment by Dogzik** [comment]
Тест на make shared с более чем одним аргументом
